### ISSUE TITLE
v3.0.0 is not installing anything

### ISSUE THREAD

**Issue by mike-potter** [phase2/generator-pattern-lab-starter#20]
After doing a "npm install --global --silent generator-pattern-lab-starter@v3.0.0", when I run "yo" it cannot find the Pattern Lab Starter generator.

Looking in /usr/local/lib/node_modules/generator-pattern-lab-starter, I do not see any "generators" folder.  All I see is README.md, node_modules, package.json.

Maybe when files were moved into the new "generators" folder this wasn't added to the build available via npm?

**Comment by EvanLovely** [comment]
Fixed in v3.0.1 ~ 6246be35230581ca3477b7a0e17d92b7e3adbc37
